## Getting hands-on with NumPy

This assignment aims at acquainting you with numpy methods which you will require during this project. So, it is advised that you follow the instructions before each code cell diligently.<br>
You are encouraged to google (or ChatGPT) things up wherever you feel stuck : )<br>
But make sure you understand things and not just copy-paste them

### **Import the NumPy library**

In [5]:
import numpy as np

### **Initialising arrays in NumPy**

NumPy offers several way to initialise arrays
* Create a $2\times3$ array identical to
$\begin{bmatrix}
1 & 2 & 4\\
7 & 13 & 21\\
\end{bmatrix}$ and a $2\times2\times3$ array identical to
$\begin{bmatrix}
[1 & 2 & 3] & [4 & 5 & 6]\\
[7 & 8 & 9] & [10 & 11 & 12]\\
\end{bmatrix}$

In [7]:
# START
    # Enter the values for the 2x3 array
arr1 = np.array([[1, 2, 4],[7, 13, 21]])
    # Similarly initialise the second array and assign it to arr2
arr2 = np.array([[[1, 2, 3], [7, 8, 9]],
                  [[4, 5, 6], [10, 11, 12]]])
# END

print("arr1:\n", arr1)
print("Shape of arr1:", arr1.shape, "; No. of Dimensions:", arr1.ndim)
print("arr2:\n", arr2)
print("Shape of arr2:", arr2.shape, "; No. of Dimensions:", arr2.ndim)

arr1:
 [[ 1  2  4]
 [ 7 13 21]]
Shape of arr1: (2, 3) ; No. of Dimensions: 2
arr2:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
Shape of arr2: (2, 2, 3) ; No. of Dimensions: 3


Note that the shapes and no. of dimensions of the arrays have been printed. These attributes help a lot in debugging

Now create
* A $2\times3$ array **arr3** of all zeros using **np.zeros**
* A $2\times3$ array **arr4** of all ones using **np.ones**
* A $2\times3$ array **arr5** of all fives using **np.full**
* A 1-D array **arr6** containing only even numbers in the range $0-20$ using **np.arange**
* Repeat last task using **np.linspace** and name it **arr7**

In [25]:
# START
arr3 = np.zeros((2,3))
arr4 = np.ones((2,3))
arr5 = np.full((2,3),5)
arr6 = np.arange(0,20,2)
arr7 = np.linspace(0,20,10, endpoint = False, dtype = int)
# END

print(f"arr3:\n {arr3}")
print(f"arr4:\n {arr4}")
print(f"arr5:\n {arr5}")
print(f"arr6:\n {arr6}")
print(f"arr7:\n {arr7}")

arr3:
 [[0. 0. 0.]
 [0. 0. 0.]]
arr4:
 [[1. 1. 1.]
 [1. 1. 1.]]
arr5:
 [[5 5 5]
 [5 5 5]]
arr6:
 [ 0  2  4  6  8 10 12 14 16 18]
arr7:
 [ 0  2  4  6  8 10 12 14 16 18]


Creating arrays with random values
* Create a $2\times3$ array **arr8** using **np.random.rand**
* Create a $2\times3$ array **arr9** with rnadom integer values in $[5,8)$ using **randint** method of **random** module

In [21]:
# START
arr8 = np.random.rand(2,3)
arr9 = np.random.randint(5, 8, size=(2, 3))
# END

print(arr8)
print(arr9)

[[0.39925066 0.97006274 0.78943069]
 [0.82293235 0.87069509 0.27929498]]
[[7 5 5]
 [6 5 5]]


### **Accessing arrays in NumPy**

Initialise an array **arr** $=
\begin{bmatrix}
1 & 3 & 5 & 7\\
9 & 11 & 13 & 15\\
17 & 19 & 21 & 23
\end{bmatrix}$ and perform the following operations:<br>

* Extract and print the element 13 using numpy array indexing
* Use array slicing to print only the 2nd and 4th columns of only the 2nd and 3rd rows of *arr*
* Print all the values in *arr* which are a multiple of 3

In [28]:
# initialization of array arr
arr = np.array([[1,3,5,7],[9,11,13,15],[17,19,21,23]])
# extracting element 13
num_13 = arr[1,2]
print(num_13)
#extraction of given rows and columns
sl_arr = arr[1:3, [1, 3]]
print ("sliced array is:\n",sl_arr)
# printing all the multiples of 3 in the given array 
ele = arr[arr % 3 == 0]
print("values which are multiple of 3 are:")
for i in range(len(ele)):
    print(ele[i])
    i += 1

13
sliced array is:
 [[11 15]
 [19 23]]
values which are multiple of 3 are:
3
9
15
21


### **Reshaping and Broadcasting**

* Reshape *arr* into a $2\times6$ matrix and print it
* Print the transpose of *arr*

In [29]:
# reshaping an array into a matrix of size 2x6
resh = arr.reshape(2,6)
print(resh)
# transpose of reshaped matrix
resh_t = np.transpose(resh)
print("transpose of matrix is:\n",resh_t)

[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]
transpose of matrix is:
 [[ 1 13]
 [ 3 15]
 [ 5 17]
 [ 7 19]
 [ 9 21]
 [11 23]]


Moving on to broadcasting, you are given two arrays **a** $=
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}$ and **b** $=
\begin{bmatrix}
4\\
5
\end{bmatrix}$<br>

Try adding these two arrays using **+** operator and print the result

In [30]:
a = np.array([1,2,3])
b = np.array([4,5]).reshape(2,1)
su = a+b
print(su)
print("dimension of sum matrix is:",su.ndim)

[[5 6 7]
 [6 7 8]]
dimension of sum matrix is: 2


You will find that NumPy repeats the values for the arrays to match dimensions and be compatible while doing a particular matrix operation. In general, a dimension is compatible if it is equal to the respective dimension of the other array or if it is 1

### **Miscellaneous**

Be cautious while multiplying matrices and don't confuse the functions doing element wise multiplication with the ones doing traditional matrix multipication.

In [31]:
a = np.array([1,2,3])
a_m = a.reshape(1,3)
a_t = np.transpose(a_m)
#print(a_t)
arr_m = arr.reshape(3,4)
arr_t = np.transpose(arr_m)
#print(arr_t)


In [33]:
# Use np.multiply and the * operator to multiply 'arr' and 'a' in this cell, note that you may need to take transpose of one or the other matrix during this operation

# here arr_t is the transpose of matrix of array "arr" and a_m is matrix of arrat "a"
prod = np.multiply(arr_t, a_m)
print(prod)
# multiply operator for multiplication
p_2 = arr_t*a_m
print(p_2)

[[ 1 18 51]
 [ 3 22 57]
 [ 5 26 63]
 [ 7 30 69]]
[[ 1 18 51]
 [ 3 22 57]
 [ 5 26 63]
 [ 7 30 69]]


In [165]:
# Use np.matmul and np.dot functions to multiply 'arr' and 'a' in this cell, again you may need to take transpose of one or the other matrix
p_3 = np.matmul(a,arr)
print(p_3) 

p_4 = np.dot(a, arr)
print(p_4)

[ 70  82  94 106]
[ 70  82  94 106]
